// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/entities/better_bots_app_state_entity.dart';
import 'data/entities/training_counter_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2029198252723419798),
    name: 'AppStateEntity',
    lastPropertyId: const obx_int.IdUid(25, 295604198934769907),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2212784577712980856),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1590776822056857052),
        name: 'playerSideName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 665127164419071245),
        name: 'skillLevel',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2575391436281521158),
        name: 'strengthModeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6342726281163414943),
        name: 'uciElo',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5651404701258538549),
        name: 'cpLossElo',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 114096986356998903),
        name: 'cpLossUciSwitchFullMoveNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 617799339624200260),
        name: 'botOpeningMoveName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4624882703898358893),
        name: 'effectiveBotOpeningMoveName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 710825412541494571),
        name: 'botPersonalityName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5462700798458000784),
        name: 'effectiveBotPersonalityName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5049034166437381619),
        name: 'personaCandidateCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2990763978790368547),
        name: 'openingLogicAllowed',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7011034310584720829),
        name: 'startFen',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 287524618805449113),
        name: 'moveListText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8636255938952638960),
        name: 'currentFen',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3330899906051444917),
        name: 'lastFrom',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 2275236937842851718),
        name: 'lastTo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 1821548665193059524),
        name: 'analysisUsedDuringCurrentGame',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 4973001145536730896),
        name: 'resultCountedForCurrentGame',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 2253833567930609600),
        name: 'updatedAtMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 2921482346686494004),
        name: 'personalitySourceName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 6889282402006407764),
        name: 'fritz19PersonalityName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 3913276451659410057),
        name: 'effectivePersonalitySourceName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 295604198934769907),
        name: 'effectiveFritz19PersonalityName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 746431534510069343),
    name: 'TrainingCounterEntity',
    lastPropertyId: const obx_int.IdUid(24, 7153153802251561993),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2637439062277687194),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1856821343745330355),
        name: 'keyHash',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 664486798015035901),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3695527571090622540),
        name: 'canonicalKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1187587527352322812),
        name: 'strengthModeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5858727088051363908),
        name: 'strengthValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1295489365918099832),
        name: 'effectiveOpeningName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1011914507695896939),
        name: 'effectivePersonalityName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 83930221721074191),
        name: 'personaCandidateCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7790516305948699222),
        name: 'cpLossUciSwitchFullMoveNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1055113017302385594),
        name: 'wonCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3225936248459853993),
        name: 'lostCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4967106633533739297),
        name: 'drawCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 453247217339290695),
        name: 'trainedCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 9113010271622736143),
        name: 'createdAtMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7414748558189126000),
        name: 'updatedAtMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8205178818581936837),
        name: 'wonWhiteCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 1125488536723410951),
        name: 'wonBlackCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 781286247546324859),
        name: 'lostWhiteCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 4079955583985020032),
        name: 'lostBlackCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 153810829324401850),
        name: 'drawWhiteCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 7307648851238883687),
        name: 'drawBlackCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 8777446922374292405),
        name: 'trainedWhiteCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 7355179185961557845),
        name: 'trainedBlackCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 7153153802251561993),
        name: 'personalitySourceName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 746431534510069343),
    lastIndexId: const obx_int.IdUid(1, 664486798015035901),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppStateEntity: obx_int.EntityDefinition<AppStateEntity>(
      model: _entities[0],
      toOneRelations: (AppStateEntity object) => [],
      toManyRelations: (AppStateEntity object) => {},
      getId: (AppStateEntity object) => object.id,
      setId: (AppStateEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AppStateEntity object, fb.Builder fbb) {
        final playerSideNameOffset = fbb.writeString(object.playerSideName);
        final strengthModeNameOffset = fbb.writeString(object.strengthModeName);
        final botOpeningMoveNameOffset = fbb.writeString(
          object.botOpeningMoveName,
        );
        final effectiveBotOpeningMoveNameOffset = fbb.writeString(
          object.effectiveBotOpeningMoveName,
        );
        final botPersonalityNameOffset = fbb.writeString(
          object.botPersonalityName,
        );
        final effectiveBotPersonalityNameOffset = fbb.writeString(
          object.effectiveBotPersonalityName,
        );
        final startFenOffset = fbb.writeString(object.startFen);
        final moveListTextOffset = fbb.writeString(object.moveListText);
        final currentFenOffset = fbb.writeString(object.currentFen);
        final lastFromOffset = fbb.writeString(object.lastFrom);
        final lastToOffset = fbb.writeString(object.lastTo);
        final personalitySourceNameOffset = fbb.writeString(
          object.personalitySourceName,
        );
        final fritz19PersonalityNameOffset = fbb.writeString(
          object.fritz19PersonalityName,
        );
        final effectivePersonalitySourceNameOffset = fbb.writeString(
          object.effectivePersonalitySourceName,
        );
        final effectiveFritz19PersonalityNameOffset = fbb.writeString(
          object.effectiveFritz19PersonalityName,
        );
        fbb.startTable(26);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, playerSideNameOffset);
        fbb.addInt64(2, object.skillLevel);
        fbb.addOffset(3, strengthModeNameOffset);
        fbb.addInt64(4, object.uciElo);
        fbb.addInt64(5, object.cpLossElo);
        fbb.addInt64(6, object.cpLossUciSwitchFullMoveNumber);
        fbb.addOffset(7, botOpeningMoveNameOffset);
        fbb.addOffset(8, effectiveBotOpeningMoveNameOffset);
        fbb.addOffset(9, botPersonalityNameOffset);
        fbb.addOffset(10, effectiveBotPersonalityNameOffset);
        fbb.addInt64(11, object.personaCandidateCount);
        fbb.addInt64(12, object.openingLogicAllowed);
        fbb.addOffset(13, startFenOffset);
        fbb.addOffset(14, moveListTextOffset);
        fbb.addOffset(15, currentFenOffset);
        fbb.addOffset(16, lastFromOffset);
        fbb.addOffset(17, lastToOffset);
        fbb.addInt64(18, object.analysisUsedDuringCurrentGame);
        fbb.addInt64(19, object.resultCountedForCurrentGame);
        fbb.addInt64(20, object.updatedAtMillis);
        fbb.addOffset(21, personalitySourceNameOffset);
        fbb.addOffset(22, fritz19PersonalityNameOffset);
        fbb.addOffset(23, effectivePersonalitySourceNameOffset);
        fbb.addOffset(24, effectiveFritz19PersonalityNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final playerSideNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final skillLevelParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final strengthModeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final uciEloParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final cpLossEloParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final cpLossUciSwitchFullMoveNumberParam = const fb.Int64Reader()
            .vTableGet(buffer, rootOffset, 16, 0);
        final botOpeningMoveNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final effectiveBotOpeningMoveNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final personalitySourceNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 46, '');
        final effectivePersonalitySourceNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 50, '');
        final botPersonalityNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final effectiveBotPersonalityNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final fritz19PersonalityNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 48, '');
        final effectiveFritz19PersonalityNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 52, '');
        final personaCandidateCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final openingLogicAllowedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final startFenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final moveListTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final currentFenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final lastFromParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final lastToParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final analysisUsedDuringCurrentGameParam = const fb.Int64Reader()
            .vTableGet(buffer, rootOffset, 40, 0);
        final resultCountedForCurrentGameParam = const fb.Int64Reader()
            .vTableGet(buffer, rootOffset, 42, 0);
        final updatedAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        final object = AppStateEntity(
          id: idParam,
          playerSideName: playerSideNameParam,
          skillLevel: skillLevelParam,
          strengthModeName: strengthModeNameParam,
          uciElo: uciEloParam,
          cpLossElo: cpLossEloParam,
          cpLossUciSwitchFullMoveNumber: cpLossUciSwitchFullMoveNumberParam,
          botOpeningMoveName: botOpeningMoveNameParam,
          effectiveBotOpeningMoveName: effectiveBotOpeningMoveNameParam,
          personalitySourceName: personalitySourceNameParam,
          effectivePersonalitySourceName: effectivePersonalitySourceNameParam,
          botPersonalityName: botPersonalityNameParam,
          effectiveBotPersonalityName: effectiveBotPersonalityNameParam,
          fritz19PersonalityName: fritz19PersonalityNameParam,
          effectiveFritz19PersonalityName: effectiveFritz19PersonalityNameParam,
          personaCandidateCount: personaCandidateCountParam,
          openingLogicAllowed: openingLogicAllowedParam,
          startFen: startFenParam,
          moveListText: moveListTextParam,
          currentFen: currentFenParam,
          lastFrom: lastFromParam,
          lastTo: lastToParam,
          analysisUsedDuringCurrentGame: analysisUsedDuringCurrentGameParam,
          resultCountedForCurrentGame: resultCountedForCurrentGameParam,
          updatedAtMillis: updatedAtMillisParam,
        );

        return object;
      },
    ),
    TrainingCounterEntity: obx_int.EntityDefinition<TrainingCounterEntity>(
      model: _entities[1],
      toOneRelations: (TrainingCounterEntity object) => [],
      toManyRelations: (TrainingCounterEntity object) => {},
      getId: (TrainingCounterEntity object) => object.id,
      setId: (TrainingCounterEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TrainingCounterEntity object, fb.Builder fbb) {
        final keyHashOffset = fbb.writeString(object.keyHash);
        final canonicalKeyOffset = fbb.writeString(object.canonicalKey);
        final strengthModeNameOffset = fbb.writeString(object.strengthModeName);
        final effectiveOpeningNameOffset = fbb.writeString(
          object.effectiveOpeningName,
        );
        final effectivePersonalityNameOffset = fbb.writeString(
          object.effectivePersonalityName,
        );
        final personalitySourceNameOffset = fbb.writeString(
          object.personalitySourceName,
        );
        fbb.startTable(25);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyHashOffset);
        fbb.addOffset(2, canonicalKeyOffset);
        fbb.addOffset(3, strengthModeNameOffset);
        fbb.addInt64(4, object.strengthValue);
        fbb.addOffset(5, effectiveOpeningNameOffset);
        fbb.addOffset(6, effectivePersonalityNameOffset);
        fbb.addInt64(7, object.personaCandidateCount);
        fbb.addInt64(8, object.cpLossUciSwitchFullMoveNumber);
        fbb.addInt64(9, object.wonCount);
        fbb.addInt64(10, object.lostCount);
        fbb.addInt64(11, object.drawCount);
        fbb.addInt64(12, object.trainedCount);
        fbb.addInt64(13, object.createdAtMillis);
        fbb.addInt64(14, object.updatedAtMillis);
        fbb.addInt64(15, object.wonWhiteCount);
        fbb.addInt64(16, object.wonBlackCount);
        fbb.addInt64(17, object.lostWhiteCount);
        fbb.addInt64(18, object.lostBlackCount);
        fbb.addInt64(19, object.drawWhiteCount);
        fbb.addInt64(20, object.drawBlackCount);
        fbb.addInt64(21, object.trainedWhiteCount);
        fbb.addInt64(22, object.trainedBlackCount);
        fbb.addOffset(23, personalitySourceNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final canonicalKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final strengthModeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final strengthValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final effectiveOpeningNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final personalitySourceNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 50, '');
        final effectivePersonalityNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final personaCandidateCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final cpLossUciSwitchFullMoveNumberParam = const fb.Int64Reader()
            .vTableGet(buffer, rootOffset, 20, 0);
        final wonCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final lostCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final drawCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final trainedCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final wonWhiteCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final wonBlackCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final lostWhiteCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final lostBlackCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          40,
          0,
        );
        final drawWhiteCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        final drawBlackCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        final trainedWhiteCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          46,
          0,
        );
        final trainedBlackCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          48,
          0,
        );
        final createdAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final updatedAtMillisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final object = TrainingCounterEntity(
          id: idParam,
          keyHash: keyHashParam,
          canonicalKey: canonicalKeyParam,
          strengthModeName: strengthModeNameParam,
          strengthValue: strengthValueParam,
          effectiveOpeningName: effectiveOpeningNameParam,
          personalitySourceName: personalitySourceNameParam,
          effectivePersonalityName: effectivePersonalityNameParam,
          personaCandidateCount: personaCandidateCountParam,
          cpLossUciSwitchFullMoveNumber: cpLossUciSwitchFullMoveNumberParam,
          wonCount: wonCountParam,
          lostCount: lostCountParam,
          drawCount: drawCountParam,
          trainedCount: trainedCountParam,
          wonWhiteCount: wonWhiteCountParam,
          wonBlackCount: wonBlackCountParam,
          lostWhiteCount: lostWhiteCountParam,
          lostBlackCount: lostBlackCountParam,
          drawWhiteCount: drawWhiteCountParam,
          drawBlackCount: drawBlackCountParam,
          trainedWhiteCount: trainedWhiteCountParam,
          trainedBlackCount: trainedBlackCountParam,
          createdAtMillis: createdAtMillisParam,
          updatedAtMillis: updatedAtMillisParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppStateEntity] entity fields to define ObjectBox queries.
class AppStateEntity_ {
  /// See [AppStateEntity.id].
  static final id = obx.QueryIntegerProperty<AppStateEntity>(
    _entities[0].properties[0],
  );

  /// See [AppStateEntity.playerSideName].
  static final playerSideName = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[1],
  );

  /// See [AppStateEntity.skillLevel].
  static final skillLevel = obx.QueryIntegerProperty<AppStateEntity>(
    _entities[0].properties[2],
  );

  /// See [AppStateEntity.strengthModeName].
  static final strengthModeName = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[3],
  );

  /// See [AppStateEntity.uciElo].
  static final uciElo = obx.QueryIntegerProperty<AppStateEntity>(
    _entities[0].properties[4],
  );

  /// See [AppStateEntity.cpLossElo].
  static final cpLossElo = obx.QueryIntegerProperty<AppStateEntity>(
    _entities[0].properties[5],
  );

  /// See [AppStateEntity.cpLossUciSwitchFullMoveNumber].
  static final cpLossUciSwitchFullMoveNumber =
      obx.QueryIntegerProperty<AppStateEntity>(_entities[0].properties[6]);

  /// See [AppStateEntity.botOpeningMoveName].
  static final botOpeningMoveName = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[7],
  );

  /// See [AppStateEntity.effectiveBotOpeningMoveName].
  static final effectiveBotOpeningMoveName =
      obx.QueryStringProperty<AppStateEntity>(_entities[0].properties[8]);

  /// See [AppStateEntity.botPersonalityName].
  static final botPersonalityName = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[9],
  );

  /// See [AppStateEntity.effectiveBotPersonalityName].
  static final effectiveBotPersonalityName =
      obx.QueryStringProperty<AppStateEntity>(_entities[0].properties[10]);

  /// See [AppStateEntity.personaCandidateCount].
  static final personaCandidateCount = obx.QueryIntegerProperty<AppStateEntity>(
    _entities[0].properties[11],
  );

  /// See [AppStateEntity.openingLogicAllowed].
  static final openingLogicAllowed = obx.QueryIntegerProperty<AppStateEntity>(
    _entities[0].properties[12],
  );

  /// See [AppStateEntity.startFen].
  static final startFen = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[13],
  );

  /// See [AppStateEntity.moveListText].
  static final moveListText = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[14],
  );

  /// See [AppStateEntity.currentFen].
  static final currentFen = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[15],
  );

  /// See [AppStateEntity.lastFrom].
  static final lastFrom = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[16],
  );

  /// See [AppStateEntity.lastTo].
  static final lastTo = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[17],
  );

  /// See [AppStateEntity.analysisUsedDuringCurrentGame].
  static final analysisUsedDuringCurrentGame =
      obx.QueryIntegerProperty<AppStateEntity>(_entities[0].properties[18]);

  /// See [AppStateEntity.resultCountedForCurrentGame].
  static final resultCountedForCurrentGame =
      obx.QueryIntegerProperty<AppStateEntity>(_entities[0].properties[19]);

  /// See [AppStateEntity.updatedAtMillis].
  static final updatedAtMillis = obx.QueryIntegerProperty<AppStateEntity>(
    _entities[0].properties[20],
  );

  /// See [AppStateEntity.personalitySourceName].
  static final personalitySourceName = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[21],
  );

  /// See [AppStateEntity.fritz19PersonalityName].
  static final fritz19PersonalityName = obx.QueryStringProperty<AppStateEntity>(
    _entities[0].properties[22],
  );

  /// See [AppStateEntity.effectivePersonalitySourceName].
  static final effectivePersonalitySourceName =
      obx.QueryStringProperty<AppStateEntity>(_entities[0].properties[23]);

  /// See [AppStateEntity.effectiveFritz19PersonalityName].
  static final effectiveFritz19PersonalityName =
      obx.QueryStringProperty<AppStateEntity>(_entities[0].properties[24]);
}

/// [TrainingCounterEntity] entity fields to define ObjectBox queries.
class TrainingCounterEntity_ {
  /// See [TrainingCounterEntity.id].
  static final id = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[0],
  );

  /// See [TrainingCounterEntity.keyHash].
  static final keyHash = obx.QueryStringProperty<TrainingCounterEntity>(
    _entities[1].properties[1],
  );

  /// See [TrainingCounterEntity.canonicalKey].
  static final canonicalKey = obx.QueryStringProperty<TrainingCounterEntity>(
    _entities[1].properties[2],
  );

  /// See [TrainingCounterEntity.strengthModeName].
  static final strengthModeName =
      obx.QueryStringProperty<TrainingCounterEntity>(
        _entities[1].properties[3],
      );

  /// See [TrainingCounterEntity.strengthValue].
  static final strengthValue = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[4],
  );

  /// See [TrainingCounterEntity.effectiveOpeningName].
  static final effectiveOpeningName =
      obx.QueryStringProperty<TrainingCounterEntity>(
        _entities[1].properties[5],
      );

  /// See [TrainingCounterEntity.effectivePersonalityName].
  static final effectivePersonalityName =
      obx.QueryStringProperty<TrainingCounterEntity>(
        _entities[1].properties[6],
      );

  /// See [TrainingCounterEntity.personaCandidateCount].
  static final personaCandidateCount =
      obx.QueryIntegerProperty<TrainingCounterEntity>(
        _entities[1].properties[7],
      );

  /// See [TrainingCounterEntity.cpLossUciSwitchFullMoveNumber].
  static final cpLossUciSwitchFullMoveNumber =
      obx.QueryIntegerProperty<TrainingCounterEntity>(
        _entities[1].properties[8],
      );

  /// See [TrainingCounterEntity.wonCount].
  static final wonCount = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[9],
  );

  /// See [TrainingCounterEntity.lostCount].
  static final lostCount = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[10],
  );

  /// See [TrainingCounterEntity.drawCount].
  static final drawCount = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[11],
  );

  /// See [TrainingCounterEntity.trainedCount].
  static final trainedCount = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[12],
  );

  /// See [TrainingCounterEntity.createdAtMillis].
  static final createdAtMillis =
      obx.QueryIntegerProperty<TrainingCounterEntity>(
        _entities[1].properties[13],
      );

  /// See [TrainingCounterEntity.updatedAtMillis].
  static final updatedAtMillis =
      obx.QueryIntegerProperty<TrainingCounterEntity>(
        _entities[1].properties[14],
      );

  /// See [TrainingCounterEntity.wonWhiteCount].
  static final wonWhiteCount = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[15],
  );

  /// See [TrainingCounterEntity.wonBlackCount].
  static final wonBlackCount = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[16],
  );

  /// See [TrainingCounterEntity.lostWhiteCount].
  static final lostWhiteCount = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[17],
  );

  /// See [TrainingCounterEntity.lostBlackCount].
  static final lostBlackCount = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[18],
  );

  /// See [TrainingCounterEntity.drawWhiteCount].
  static final drawWhiteCount = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[19],
  );

  /// See [TrainingCounterEntity.drawBlackCount].
  static final drawBlackCount = obx.QueryIntegerProperty<TrainingCounterEntity>(
    _entities[1].properties[20],
  );

  /// See [TrainingCounterEntity.trainedWhiteCount].
  static final trainedWhiteCount =
      obx.QueryIntegerProperty<TrainingCounterEntity>(
        _entities[1].properties[21],
      );

  /// See [TrainingCounterEntity.trainedBlackCount].
  static final trainedBlackCount =
      obx.QueryIntegerProperty<TrainingCounterEntity>(
        _entities[1].properties[22],
      );

  /// See [TrainingCounterEntity.personalitySourceName].
  static final personalitySourceName =
      obx.QueryStringProperty<TrainingCounterEntity>(
        _entities[1].properties[23],
      );
}
